import { Product } from '@/types';

export const products: Product[] = [
  {
    id: '1',
    slug: 'smrtq-portable-500',
    name: 'smrtQ Portable 500',
    tagline: 'Light. Mighty. Ready.',
    description:
      'The smrtQ Portable 500 packs 500Wh of clean power into a travel-friendly form factor. Perfect for camping trips, outdoor events, and keeping essentials running during short outages. LFP battery chemistry ensures 3,500+ charge cycles.',
    category: 'power-station',
    capacity: '500Wh',
    wattage: '700W',
    price: { NG: 420000, AE: 1400, SA: 1450 },
    originalPrice: { NG: 480000, AE: 1599, SA: 1649 },
    badge: 'Best Value',
    isNew: false,
    isBestseller: false,
    inStock: true,
    features: [
      '500Wh LFP Battery — 3,500+ cycles',
      '700W AC Output (1,400W surge)',
      'Charges 0–80% in 1 hour via wall',
      'Solar input up to 200W',
      '2× AC, 2× USB-A, 1× USB-C, 1× DC',
      'App monitoring via Bluetooth',
      'Silent fanless operation',
      'Weight: 6.5 kg',
    ],
    specs: [
      { label: 'Capacity', value: '500Wh' },
      { label: 'AC Output', value: '700W (1,400W surge)' },
      { label: 'AC Ports', value: '2 × AC Outlets' },
      { label: 'USB-A', value: '2 × 18W Quick Charge' },
      { label: 'USB-C', value: '1 × 100W PD' },
      { label: 'DC Output', value: '12V/10A' },
      { label: 'Solar Input', value: 'Max 200W, 12–30V' },
      { label: 'Wall Charge Time', value: '≈ 1.5 hrs (0–100%)' },
      { label: 'Battery Type', value: 'LiFePO4 (LFP)' },
      { label: 'Cycle Life', value: '3,500+ cycles to 80%' },
      { label: 'Weight', value: '6.5 kg' },
      { label: 'Dimensions', value: '28 × 19 × 21 cm' },
      { label: 'Operating Temp', value: '-10°C to 40°C' },
      { label: 'Warranty', value: '5 Years' },
    ],
    reviews: [
      {
        id: 'r1',
        name: 'Emeka O.',
        country: 'NG',
        rating: 5,
        comment: 'This thing is a lifesaver during NEPA cuts. Runs my fan, lights, and phone for hours. Very happy with the purchase!',
        date: '2024-11-10',
      },
      {
        id: 'r2',
        name: 'Fatima A.',
        country: 'AE',
        rating: 5,
        comment: 'Took it on our desert camping trip. Charged phones, a speaker, and small lights all night. Compact and powerful.',
        date: '2024-12-03',
      },
      {
        id: 'r3',
        name: 'Mohammed K.',
        country: 'SA',
        rating: 4,
        comment: 'Great unit. Setup was easy and the app works well. Slight deduction for the fan being audible at high load.',
        date: '2025-01-15',
      },
    ],
    images: ['/images/portable-500-1.jpg', '/images/portable-500-2.jpg'],
  },
  {
    id: '2',
    slug: 'smrtq-pro-1000',
    name: 'smrtQ Pro 1000',
    tagline: 'Home Power. Redefined.',
    description:
      'The smrtQ Pro 1000 delivers 1,000Wh of dependable power with a robust 1,500W AC output. Designed for home backup, remote work, and outdoor living. Features smart app control and dual fast-charging inputs.',
    category: 'power-station',
    capacity: '1000Wh',
    wattage: '1500W',
    price: { NG: 850000, AE: 2800, SA: 2900 },
    originalPrice: { NG: 950000, AE: 3199, SA: 3299 },
    badge: 'Most Popular',
    isNew: false,
    isBestseller: true,
    inStock: true,
    features: [
      '1,000Wh LFP Battery — 3,500+ cycles',
      '1,500W AC Output (3,000W surge)',
      'Dual charging: Wall + Solar simultaneously',
      'Solar input up to 400W',
      '3× AC, 2× USB-A, 2× USB-C, 2× DC',
      'Full-colour LCD display',
      'Remote control via smrtQ App',
      'Weight: 11.5 kg',
    ],
    specs: [
      { label: 'Capacity', value: '1,000Wh' },
      { label: 'AC Output', value: '1,500W (3,000W surge)' },
      { label: 'AC Ports', value: '3 × AC Outlets' },
      { label: 'USB-A', value: '2 × 18W Quick Charge' },
      { label: 'USB-C', value: '2 × 100W PD' },
      { label: 'DC Output', value: '12V/10A × 2' },
      { label: 'Solar Input', value: 'Max 400W, 12–60V' },
      { label: 'Wall Charge Time', value: '≈ 1.8 hrs (0–100%)' },
      { label: 'Battery Type', value: 'LiFePO4 (LFP)' },
      { label: 'Cycle Life', value: '3,500+ cycles to 80%' },
      { label: 'Weight', value: '11.5 kg' },
      { label: 'Dimensions', value: '38 × 24 × 28 cm' },
      { label: 'Operating Temp', value: '-10°C to 40°C' },
      { label: 'Warranty', value: '5 Years' },
    ],
    reviews: [
      {
        id: 'r4',
        name: 'Chukwudi N.',
        country: 'NG',
        rating: 5,
        comment: 'Best investment I have made for my home. No more generator noise or fuel cost. Runs my fridge, TV and lights perfectly.',
        date: '2025-01-20',
      },
      {
        id: 'r5',
        name: 'Khalid M.',
        country: 'AE',
        rating: 5,
        comment: 'Excellent quality. Used it for a week-long glamping trip and it performed flawlessly. The app is very intuitive.',
        date: '2024-12-18',
      },
      {
        id: 'r6',
        name: 'Sara Al-H.',
        country: 'SA',
        rating: 5,
        comment: 'Purchased for our chalet in the mountains. Handles air conditioning and cooking appliances without breaking a sweat.',
        date: '2025-02-05',
      },
    ],
    images: ['/images/pro-1000-1.jpg', '/images/pro-1000-2.jpg'],
  },
  {
    id: '3',
    slug: 'smrtq-ultra-2000',
    name: 'smrtQ Ultra 2000',
    tagline: 'Whole Home. Zero Interruptions.',
    description:
      'Our flagship power station. 2,000Wh of premium LFP capacity with a massive 2,400W AC output handles virtually any appliance. Built for serious home backup, businesses, and off-grid living. Expandable with additional battery modules.',
    category: 'power-station',
    capacity: '2000Wh',
    wattage: '2400W',
    price: { NG: 1650000, AE: 5400, SA: 5600 },
    badge: 'Flagship',
    isNew: true,
    isBestseller: false,
    inStock: true,
    features: [
      '2,000Wh LFP Battery — 3,500+ cycles',
      '2,400W AC Output (4,800W surge)',
      'Solar input up to 1,200W',
      'Wall-to-full in under 2 hours',
      '4× AC, 2× USB-A, 3× USB-C, 2× DC, 1× RV',
      'Smart EPS — switches in <30ms',
      'Expandable to 6,000Wh with add-on batteries',
      'Weight: 22 kg',
    ],
    specs: [
      { label: 'Capacity', value: '2,000Wh' },
      { label: 'AC Output', value: '2,400W (4,800W surge)' },
      { label: 'AC Ports', value: '4 × AC Outlets' },
      { label: 'USB-A', value: '2 × 18W Quick Charge' },
      { label: 'USB-C', value: '3 × 140W PD' },
      { label: 'DC Output', value: '12V/30A × 2' },
      { label: 'Car Port', value: '12V/25A' },
      { label: 'Solar Input', value: 'Max 1,200W, 12–150V' },
      { label: 'Wall Charge Time', value: '≈ 1.5 hrs (0–100%)' },
      { label: 'Battery Type', value: 'LiFePO4 (LFP)' },
      { label: 'Cycle Life', value: '3,500+ cycles to 80%' },
      { label: 'EPS Switchover', value: '<30ms' },
      { label: 'Weight', value: '22 kg' },
      { label: 'Dimensions', value: '51 × 28 × 36 cm' },
      { label: 'Warranty', value: '5 Years' },
    ],
    reviews: [
      {
        id: 'r7',
        name: 'Adaeze I.',
        country: 'NG',
        rating: 5,
        comment:
          'This is the real deal. My entire household runs on this now. AC, fridge, microwave — all going simultaneously. Best purchase of 2025.',
        date: '2025-03-01',
      },
      {
        id: 'r8',
        name: 'Omar S.',
        country: 'AE',
        rating: 5,
        comment:
          'Installed this at our beach house. Powers everything including the AC unit during the day when paired with the 400W solar panel.',
        date: '2025-02-14',
      },
    ],
    images: ['/images/ultra-2000-1.jpg', '/images/ultra-2000-2.jpg'],
  },
  {
    id: '4',
    slug: 'smrtq-solar-panel-200w',
    name: 'smrtQ Solar 200W',
    tagline: 'Harvest the Sun.',
    description:
      'Foldable, monocrystalline solar panel with 23.4% efficiency. Pairs perfectly with the smrtQ Portable 500 and Pro 1000. Features an intelligent MPPT controller and integrated kickstand.',
    category: 'solar-panel',
    wattage: '200W',
    price: { NG: 185000, AE: 620, SA: 640 },
    isNew: false,
    isBestseller: false,
    inStock: true,
    features: [
      '200W monocrystalline cells',
      '23.4% conversion efficiency',
      'Built-in MPPT charge controller',
      'Foldable — fits in a carry bag',
      'IP67 waterproof connectors',
      'Compatible with all smrtQ stations',
      'Works in partial shade',
      'Weight: 5.4 kg',
    ],
    specs: [
      { label: 'Rated Power', value: '200W' },
      { label: 'Cell Type', value: 'Monocrystalline' },
      { label: 'Efficiency', value: '23.4%' },
      { label: 'Open Circuit Voltage', value: '24.3V' },
      { label: 'Short Circuit Current', value: '9.6A' },
      { label: 'Connector', value: 'XT60 + MC4' },
      { label: 'Waterproof', value: 'IP67 connectors' },
      { label: 'Folded Size', value: '60 × 54 × 5 cm' },
      { label: 'Weight', value: '5.4 kg' },
      { label: 'Warranty', value: '2 Years' },
    ],
    reviews: [
      {
        id: 'r9',
        name: 'Tunde B.',
        country: 'NG',
        rating: 5,
        comment: 'Charges my Pro 1000 fully by noon! Great panel for the price.',
        date: '2025-01-30',
      },
    ],
    images: ['/images/solar-200w-1.jpg'],
  },
  {
    id: '5',
    slug: 'smrtq-solar-panel-400w',
    name: 'smrtQ Solar 400W',
    tagline: 'Maximum Solar Harvest.',
    description:
      'Our highest-output portable solar panel. 400W of monocrystalline power in a durable, foldable design. Ideal for rapidly charging the smrtQ Ultra 2000 or running as a small off-grid solar system.',
    category: 'solar-panel',
    wattage: '400W',
    price: { NG: 340000, AE: 1150, SA: 1190 },
    badge: 'New',
    isNew: true,
    isBestseller: false,
    inStock: true,
    features: [
      '400W monocrystalline cells',
      '23.6% conversion efficiency',
      'Dual MPPT ports — connect two stations',
      'Integrated adjustable kickstand (0°–60°)',
      'IP68 waterproof connectors',
      'Anti-reflective tempered glass surface',
      'Works in low-light & cloudy conditions',
      'Weight: 9.8 kg',
    ],
    specs: [
      { label: 'Rated Power', value: '400W' },
      { label: 'Cell Type', value: 'Monocrystalline' },
      { label: 'Efficiency', value: '23.6%' },
      { label: 'Open Circuit Voltage', value: '48.2V' },
      { label: 'Short Circuit Current', value: '9.8A' },
      { label: 'Connector', value: 'XT60 + MC4 × 2' },
      { label: 'Waterproof', value: 'IP68 connectors' },
      { label: 'Folded Size', value: '75 × 54 × 6 cm' },
      { label: 'Weight', value: '9.8 kg' },
      { label: 'Warranty', value: '2 Years' },
    ],
    reviews: [
      {
        id: 'r10',
        name: 'Abdullah R.',
        country: 'SA',
        rating: 5,
        comment: 'Paired with the Ultra 2000. Together they power my whole campsite independently. Incredible system.',
        date: '2025-03-10',
      },
    ],
    images: ['/images/solar-400w-1.jpg'],
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.category === 'power-station');
}
