import { Product } from '@/types';

export const products: Product[] = [
  {
    id: 'q-08',
    slug: 'q-08-512wh',
    name: 'smrtQ Q-08',
    tagline: 'Compact Power for Every Adventure',
    description:
      'The Q-08 packs 512Wh of safe LiFePO4 energy into a carry-anywhere 6.5 kg form factor. With an 800W pure sine wave output, 8 ports, and a 1.5-hour charge time, it keeps all your essentials powered on the road, at the campsite, or through any outage.',
    category: 'power-station',
    capacity: '512Wh',
    wattage: '800W',
    price: { NG: 320000, AE: 1050, SA: 1090 },
    originalPrice: { NG: 380000, AE: 1250, SA: 1290 },
    badge: 'Best Value',
    isNew: false,
    isBestseller: false,
    inStock: true,
    compareData: { chargeTime: '1.5 hrs', solarIn: '200W', ports: '8', cycles: '4,000+' },
    features: [
      '512Wh LiFePO4 battery — 4,000+ charge cycles',
      '800W AC pure sine wave output',
      'Charges 0–100% in 1.5 hours (400W AC input)',
      'Solar input up to 200W (MPPT)',
      '8 ports: USB-A QC3.0 ×2, USB-C PD 100W ×1, PD 20W ×2, AC, DC, Cigar',
      'UPS mode — seamless switchover in <10ms',
      'Fireproof shell (Level 94v-0)',
      '5W built-in LED light',
      'Battery Management System (BMS)',
    ],
    specs: [
      { label: 'Model No.', value: 'Q-08 (N054)' },
      { label: 'Capacity', value: '512Wh' },
      { label: 'Battery Type', value: 'LiFePO4 #40135' },
      { label: 'Cycle Life', value: '4,000+ cycles' },
      { label: 'AC Output', value: '800W Max — Pure Sine Wave' },
      { label: 'AC Ports', value: '1 × AC Outlet' },
      { label: 'USB-A', value: '2 × QC 3.0' },
      { label: 'USB-C (PD)', value: '1 × 100W + 2 × 20W' },
      { label: 'DC Output', value: 'DC6530 (12V/10A) ×1' },
      { label: 'Cigar Output', value: '12V / 10A ×1' },
      { label: 'Solar Input', value: 'Max 200W (MPPT, via XT60)' },
      { label: 'AC Input', value: 'Max 400W' },
      { label: 'AC Charge Time', value: '≈1.5 hrs (0–100%)' },
      { label: 'UPS Switchover', value: '<10ms' },
      { label: 'Shell', value: 'Fireproof Level 94v-0' },
      { label: 'LED Light', value: '5W High Brightness' },
      { label: 'Working Temp', value: '-10°C to 45°C' },
      { label: 'Dimensions', value: '276 × 209 × 230 mm' },
      { label: 'Weight', value: '6.5 kg' },
      { label: 'Ports Total', value: '8' },
    ],
    reviews: [
      {
        id: 'r1',
        name: 'Emeka O.',
        country: 'NG',
        rating: 5,
        comment:
          'This is exactly what I needed for NEPA cuts. Runs my fan, LED lights, and charges my phone and laptop all night. Compact enough to keep in my room permanently.',
        date: '2025-01-10',
      },
      {
        id: 'r2',
        name: 'Fatima A.',
        country: 'AE',
        rating: 5,
        comment:
          'Took it to Hatta for a camping weekend. Charged phones, powered a speaker, and kept a small cooler going. Perfect size for travel.',
        date: '2025-02-03',
      },
      {
        id: 'r3',
        name: 'Mohammed K.',
        country: 'SA',
        rating: 4,
        comment:
          'Good unit. 1.5 hour charge is accurate. The UPS switchover was seamless during a power flicker — my PC never noticed.',
        date: '2025-01-15',
      },
    ],
    images: ['/assets/products/N054_sheet.jpg'],
  },
  {
    id: 'q-12',
    slug: 'q-12-1024wh',
    name: 'smrtQ Q-12',
    tagline: 'Powerful, Fast, Reliable Portable Energy',
    description:
      'The Q-12 delivers 1024Wh of LiFePO4 capacity with a class-leading 1.2-hour charge time. At 1200W pure sine wave output, it runs laptops, routers, fans, small fridges, and power tools. The go-to choice for daily home backup and serious outdoor use.',
    category: 'power-station',
    capacity: '1024Wh',
    wattage: '1200W',
    price: { NG: 600000, AE: 1950, SA: 2020 },
    originalPrice: { NG: 720000, AE: 2350, SA: 2430 },
    badge: 'Most Popular',
    isNew: false,
    isBestseller: true,
    inStock: true,
    compareData: { chargeTime: '1.2 hrs', solarIn: '200W', ports: '8', cycles: '3,500+' },
    features: [
      '1024Wh LiFePO4 battery — 3,500+ charge cycles',
      '1200W AC pure sine wave output',
      'Fastest in class: 0–100% in 1.2 hours (1000W AC input)',
      'Solar input up to 200W (MPPT)',
      '8 ports: USB-A QC3.0 ×2, USB-C PD 100W ×1, PD 20W ×1, AC, Cigar, DC',
      'UPS mode — seamless switchover in <10ms',
      'Fireproof shell (Level 94v-0)',
      '10W built-in LED light (brighter than Q-08)',
      'Battery Management System (BMS)',
    ],
    specs: [
      { label: 'Model No.', value: 'Q-12 (N077)' },
      { label: 'Capacity', value: '1024Wh' },
      { label: 'Battery Type', value: 'LiFePO4 #40135' },
      { label: 'Cycle Life', value: '3,500+ cycles' },
      { label: 'AC Output', value: '1200W Max — Pure Sine Wave' },
      { label: 'USB-A', value: '2 × QC 3.0' },
      { label: 'USB-C (PD)', value: '1 × 100W + 1 × 20W' },
      { label: 'Cigar Output', value: '12V / 10A ×1' },
      { label: 'XT60 Solar Input', value: 'Max 200W (11.5V–50V)' },
      { label: 'AC Input', value: 'Max 1000W' },
      { label: 'AC Charge Time', value: '≈1.2 hrs (0–100%)' },
      { label: 'UPS Switchover', value: '<10ms' },
      { label: 'Shell', value: 'Fireproof Level 94v-0' },
      { label: 'LED Light', value: '10W High Brightness' },
      { label: 'Working Temp', value: '-10°C to 45°C' },
      { label: 'Dimensions', value: '329 × 205 × 273 mm' },
      { label: 'Weight', value: '12 kg' },
      { label: 'Ports Total', value: '8' },
    ],
    reviews: [
      {
        id: 'r4',
        name: 'Chukwudi N.',
        country: 'NG',
        rating: 5,
        comment:
          'Best purchase of the year. Runs my fridge, TV, router, and all phone chargers all through the night. Generator is now collecting dust.',
        date: '2025-01-20',
      },
      {
        id: 'r5',
        name: 'Khalid M.',
        country: 'AE',
        rating: 5,
        comment:
          'Used it for a week of desert camping. The 1.2-hour charge time is real — I verified it. Handles a small electric kettle without issue.',
        date: '2024-12-18',
      },
      {
        id: 'r6',
        name: 'Sara Al-H.',
        country: 'SA',
        rating: 5,
        comment:
          'Bought it for our farm office. Keeps the computers, printer, and lighting running all day. The UPS feature saved us during a sudden grid trip.',
        date: '2025-02-05',
      },
    ],
    images: ['/assets/products/N077_sheet.jpg'],
  },
  {
    id: 'q-24',
    slug: 'q-24-2048wh',
    name: 'smrtQ Q-24',
    tagline: 'Home-Grade Power That Goes Anywhere',
    description:
      'The Q-24 brings 2048Wh of premium LiFePO4 power with a 2400W pure sine wave output across 3 AC outlets. Featuring 13 total ports, 500W solar input, a 5-level adjustable input power knob, and pass-through charging — it handles full home backup, RV, and serious outdoor setups with ease.',
    category: 'power-station',
    capacity: '2048Wh',
    wattage: '2400W',
    price: { NG: 1150000, AE: 3800, SA: 3940 },
    badge: 'Pro Choice',
    isNew: true,
    isBestseller: false,
    inStock: true,
    compareData: { chargeTime: '1.8 hrs', solarIn: '500W', ports: '13', cycles: '4,000+' },
    features: [
      '2048Wh LiFePO4 battery — 4,000+ charge cycles',
      '2400W pure sine wave output across 3 AC outlets',
      'Adjustable input power knob: 300 / 500 / 700 / 900 / 1100W',
      'Solar input up to 500W (MPPT)',
      'Pass-through charging supported',
      '13 ports: USB-A QC3.0 ×2, USB-C PD 100W ×1, PD 20W ×3, DC5521 ×2, XT60, Cigar, AC ×3',
      'UPS mode — seamless switchover in <10ms',
      'Fireproof ABS shell with storage compartment',
      'Hyper Fast Charging technology',
    ],
    specs: [
      { label: 'Model No.', value: 'Q-24 (N052)' },
      { label: 'Capacity', value: '2048Wh' },
      { label: 'Battery Type', value: 'LiFePO4 #40135' },
      { label: 'Cycle Life', value: '4,000+ cycles' },
      { label: 'AC Output', value: '2400W × 3 Ports — Pure Sine Wave' },
      { label: 'USB-A', value: '2 × QC 3.0' },
      { label: 'USB-C (PD)', value: '1 × 100W + 3 × 20W' },
      { label: 'DC Output', value: 'DC5521 (12V/3A) ×2 + XT60 (12V/25A) ×1' },
      { label: 'Cigar Output', value: '13.6V / 10A ×1' },
      { label: 'Solar Input', value: 'Max 500W (MPPT)' },
      { label: 'AC Input', value: 'Adjustable: 300/500/700/900/1100W' },
      { label: 'AC Charge Time', value: '≈1.8 hrs (0–100% at 1100W)' },
      { label: 'Pass-Through', value: 'Yes — supported' },
      { label: 'UPS Switchover', value: '<10ms' },
      { label: 'Shell', value: 'Fireproof ABS + Storage Compartment' },
      { label: 'Working Temp', value: '-10°C to 45°C' },
      { label: 'Dimensions', value: '386 × 284 × 321 mm' },
      { label: 'Weight', value: '22.5 kg' },
      { label: 'Ports Total', value: '13' },
    ],
    reviews: [
      {
        id: 'r7',
        name: 'Adaeze I.',
        country: 'NG',
        rating: 5,
        comment:
          'Runs my entire flat — AC, fridge, microwave, washing machine (short cycles), TVs and all chargers. The whole family is off the generator permanently now.',
        date: '2025-03-01',
      },
      {
        id: 'r8',
        name: 'Omar S.',
        country: 'AE',
        rating: 5,
        comment:
          'Running our beach house fully off-grid with two 200W panels. The pass-through charging means it charges and powers loads simultaneously. Outstanding product.',
        date: '2025-02-14',
      },
    ],
    images: ['/assets/products/N052_sheet.jpg'],
  },
  {
    id: 'q-36',
    slug: 'q-36-3840wh',
    name: 'smrtQ Q-36',
    tagline: 'Industrial Strength. Portable Freedom.',
    description:
      'Our most powerful station. The Q-36 delivers 3840Wh expandable to 11,520Wh (with 2× Q-36B packs), a massive 3600W output, 2000W solar input, and 15 ports — all on wheels with a pull rod for mobility. Designed for whole-home backup, construction sites, RV, and off-grid living.',
    category: 'power-station',
    capacity: '3840Wh',
    wattage: '3600W',
    price: { NG: 2200000, AE: 7200, SA: 7460 },
    badge: 'Flagship',
    isFlagship: true,
    isNew: true,
    isBestseller: false,
    inStock: true,
    compareData: { chargeTime: '3 hrs', solarIn: '2000W', ports: '15', cycles: '4,000+' },
    features: [
      '3840Wh LiFePO4 battery — 4,000+ charge cycles',
      '3600W (220V) / 3300W (110V) pure sine wave output',
      'Expandable to 11,520Wh with 2× Q-36B battery packs',
      'Solar input up to 2000W (MPPT) — fastest in range',
      '15 ports: USB-A QC3.0 ×2, USB-C PD 100W ×1, PD 20W ×3, DC5521 ×2, XT60, Cigar, AC ×3',
      'UPS mode — seamless switchover in <10ms',
      'Mobility wheels + pull rod — easy transport at 42 kg',
      'Fireproof shell (Level 94v-0)',
      'Adjustable host power input',
    ],
    specs: [
      { label: 'Model No.', value: 'Q-36 (N066)' },
      { label: 'Capacity', value: '3840Wh (expandable to 11,520Wh)' },
      { label: 'Battery Type', value: 'LiFePO4 #40135' },
      { label: 'Cycle Life', value: '4,000+ cycles' },
      { label: 'AC Output', value: '3600W (220V) / 3300W (110V) — Pure Sine Wave' },
      { label: 'AC Ports', value: '3 × AC Outlets' },
      { label: 'USB-A', value: '2 × QC 3.0' },
      { label: 'USB-C (PD)', value: '1 × 100W + 3 × 20W' },
      { label: 'DC Output', value: 'DC5521 (12V/3A) ×2 + XT60 (12V/25A) ×1' },
      { label: 'Cigar Output', value: '12V / 10A ×1' },
      { label: 'Solar Input', value: 'Max 2000W (MPPT)' },
      { label: 'AC Input', value: 'Max 2200W (220V)' },
      { label: 'AC Charge Time', value: '≈3 hrs (0–100%)' },
      { label: 'Expansion', value: 'Q-36B pack ×2 → 11,520Wh total' },
      { label: 'UPS Switchover', value: '<10ms' },
      { label: 'Mobility', value: 'Wheels + pull rod' },
      { label: 'Shell', value: 'Fireproof Level 94v-0' },
      { label: 'LED Light', value: '5W High Brightness' },
      { label: 'Working Temp', value: '-10°C to 45°C' },
      { label: 'Dimensions', value: '550 × 321 × 464 mm' },
      { label: 'Weight', value: '42 kg (host) + 36.5 kg per Q-36B' },
      { label: 'Ports Total', value: '15' },
    ],
    reviews: [
      {
        id: 'r9',
        name: 'Tunde B.',
        country: 'NG',
        rating: 5,
        comment:
          'Running my entire compound — 3 apartments, a shop, and CCTV — all from one Q-36 with two solar panels. Best investment in years.',
        date: '2025-02-28',
      },
      {
        id: 'r10',
        name: 'Abdullah R.',
        country: 'SA',
        rating: 5,
        comment:
          'We use this at our construction sites. Runs power tools, site lighting, a computer and printer simultaneously. The wheels make it practical at 42kg.',
        date: '2025-03-10',
      },
    ],
    images: ['/assets/products/N066_sheet.jpg'],
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}
